# syntax=docker/dockerfile:1

# ------------------------------------------------
# Build stage
# ------------------------------------------------
FROM maven:3.9-eclipse-temurin-21 AS builder

WORKDIR /workspace

COPY pom.xml .
RUN mvn -B dependency:go-offline

COPY src ./src
RUN mvn -B clean package -DskipTests


# ------------------------------------------------
# Standard runtime
# ------------------------------------------------
FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=builder \
/workspace/target/cloud-native-demo-services-0.0.1-SNAPSHOT.jar \
/app/app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]